#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.gcp-setup.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else false; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any, with write_env's quoting undone.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line value sq="'\\''"; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  value="${line#*=}"
  if [[ "$value" == \'*\' ]]; then value="${value:1:${#value}-2}"; value="${value//"$sq"/\'}"; fi
  printf '%s' "$value"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret), edited
# with Readline. Fails at EOF with no input.
ask() {
  local key="$1" prompt="$2" current input s=$'\001' e=$'\002' p rc=0
  current=$(_existing "$key" || true)
  # Readline needs the colour codes wrapped in \001..\002 to place the cursor.
  p="  $s$BOLD$e$prompt$s$RESET$e "
  [[ -n "$current" ]] && p+="$s$DIM$e[Enter keeps current]$s$RESET$e "
  read -e -r -p "$p" input || rc=1
  if (( rc )) && [[ -z "$input" ]]; then return 1; fi
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input rc=0
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || rc=1
  printf '\n'
  if (( rc )) && [[ -z "$input" ]]; then return 1; fi
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY='VALUE' into ENV_FILE (replaces any existing
# line). Idempotent. Creates ENV_FILE at mode 0600; writes through a symlink
# and keeps an existing file's mode.
write_env() {
  local key="$1" value="$2" tmp sq="'\\''"
  [[ -e "$ENV_FILE" ]] || (umask 077 && : > "$ENV_FILE")
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf "%s='%s'\n" "$key" "${value//\'/$sq}" >> "$tmp"
  cat "$tmp" > "$ENV_FILE"
  rm -f "$tmp"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES: remaining GCP setup for the C# API (docs/port/gcp-setup-checklist.md, #534)
# Project, APIs, registry, IAM, Vercel details and the build trigger are already done and were removed.
#
# Resumable: every stage first inspects the real state (gcloud / gh) and skips
# what is already done, so re-running after a failure or Ctrl-C is always safe.
# Non-secret answers live in .gcp-setup.env (gitignored). The DB password is
# never saved. No GitHub secrets are set: the checklist wants Actions to hold none.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4
REGION="europe-west1"
REPO_SLUG="TFordyce/roll-for-brew"
REPO_NAME="rfb-api"                    # Artifact Registry repository
SERVICE="rfb-api"                      # Cloud Run service
TRIGGER="rfb-api-deploy"
SECRET_NAME="rfb-api-postgres-connection-string"

# open_url URL: the library version hands URLs to explorer.exe on Windows (Git Bash), which opens the
# file system for URLs containing ';' or '?'. Use PowerShell's Start-Process there instead.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s
' "$GREEN" "$RESET" "$url"
  { if   command -v powershell.exe >/dev/null 2>&1; then powershell.exe -NoProfile -Command "Start-Process '$url'"
    elif command -v wslview        >/dev/null 2>&1; then wslview "$url"
    elif command -v xdg-open       >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open           >/dev/null 2>&1; then open "$url"
    else false; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

ok() { printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"; }

# skip_stage "why": the stage's work is already done; show it briefly, move on.
skip_stage() { ok "$1"; sleep 2; }

# run_now CMD...: print and run a command; a failure warns instead of aborting.
run_now() {
  printf '\n  %s$ %s%s\n' "$DIM" "$*" "$RESET"
  "$@" || warn "that command failed, check the output above"
}

# run_cmd CMD...: like run_now, but asks first; declined commands are listed at the end.
run_cmd() {
  printf '\n  %s$ %s%s\n' "$DIM" "$*" "$RESET"
  if confirm "Run this now?"; then
    "$@" || warn "that command failed, check the output above"
  else
    SKIPPED+=("$*")
  fi
}

# ask_valid KEY "Prompt" REGEX "error": reuse the saved value if it's valid,
# otherwise ask until the answer matches.
ask_valid() {
  local key="$1" prompt="$2" re="$3" err="$4" cur
  cur=$(_existing "$key" || true)
  if [[ -n "$cur" && "$cur" =~ $re ]]; then printf -v "$key" '%s' "$cur"; return 0; fi
  while true; do
    ask "$key" "$prompt" || exit 1
    [[ "${!key}" =~ $re ]] && break
    warn "$err"
  done
}

# countdown SECONDS "label": live countdown; Enter skips it.
countdown() {
  local left="$1" label="$2"
  while (( left > 0 )); do
    printf '\r  %s%s: %02d:%02d left (Enter to skip)%s   ' "$DIM" "$label" $((left / 60)) $((left % 60)) "$RESET"
    if read -r -t 1 _; then break; fi
    left=$((left - 1))
  done
  printf '\r%*s\r' 70 ''
}

service_field() { # gcloud format key
  gcloud run services describe "$SERVICE" --region "$REGION" --project "$GCP_PROJECT_ID" \
    --format="value($1)" 2>/dev/null || true
}

# ── Preflight: who am I? ──────────────────────────────────────────────────
GCLOUD_ACCOUNT=$(gcloud auth list --filter=status:ACTIVE --format='value(account)' 2>/dev/null | head -n1 || true)
if [[ -z "$GCLOUD_ACCOUNT" ]]; then
  printf 'No active gcloud account. Run "gcloud auth login" (or "gcloud config set account ACCOUNT"), then re-run.\n' >&2
  exit 1
fi

banner "GCP setup for the C# API: remaining steps (ticket #534)"
say "Signed in to gcloud as: $GCLOUD_ACCOUNT"
confirm "Is that the right account?" || { printf 'Switch with "gcloud config set account ACCOUNT" or "gcloud auth login", then re-run.\n' >&2; exit 1; }

# ── Saved project ─────────────────────────────────────────────────────────
GCP_PROJECT_ID=$(_existing GCP_PROJECT_ID || true)
if [[ -z "$GCP_PROJECT_ID" ]] || ! gcloud projects describe "$GCP_PROJECT_ID" >/dev/null 2>&1; then
  ask_valid GCP_PROJECT_ID "Google Cloud Project ID:" '^[a-z][a-z0-9-]{4,28}[a-z0-9]$' "Expected a project ID like my-project-123."
  gcloud projects describe "$GCP_PROJECT_ID" >/dev/null 2>&1 || { warn "gcloud can't see project '$GCP_PROJECT_ID'. Check the ID and account."; exit 1; }
  write_env GCP_PROJECT_ID "$GCP_PROJECT_ID"
fi
ok "Project $GCP_PROJECT_ID"
sleep 1

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Database connection string (Secret Manager)"
ask_valid SUPABASE_PROJECT_REF "Supabase project ref (20 letters, from your Supabase URL):" \
  '^[a-z0-9]{20}$' "Expected 20 lowercase letters/digits, e.g. abcdefghijklmnopqrst."
write_env SUPABASE_PROJECT_REF "$SUPABASE_PROJECT_REF"
SECRET_VERSION=$(gcloud secrets versions list "$SECRET_NAME" --project "$GCP_PROJECT_ID" \
  --filter='state=ENABLED' --format='value(name)' --limit=1 2>/dev/null || true)
REPLACE_SECRET=no
if [[ -n "$SECRET_VERSION" ]]; then
  ok "Secret '$SECRET_NAME' has an enabled version (v$SECRET_VERSION)"
  note "Once migration 0157 is live and the rfb_api password is set (docs/port/rfb-api-role-runbook.md),"
  note "answer yes below to replace it with the real rfb_api connection string."
  confirm "Replace the connection string now?" && REPLACE_SECRET=yes
else
  REPLACE_SECRET=yes
fi
if [[ "$REPLACE_SECRET" == "yes" ]]; then
  say ""
  say "[Supabase dashboard] Project > Connect > Transaction pooler (port 6543)."
  open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}?showConnect=true"
  step "From the pooler string, copy the host: aws-0-<region>.pooler.supabase.com"
  ask_valid SUPABASE_POOLER_HOST "Pooler host:" '^aws-[a-z0-9-]+\.pooler\.supabase\.com$' \
    "Expected only the host, e.g. aws-0-eu-west-1.pooler.supabase.com"
  write_env SUPABASE_POOLER_HOST "$SUPABASE_POOLER_HOST"
  while true; do
    ask_secret RFB_API_DB_PASSWORD "Paste the rfb_api password (nothing shows as you paste), then Enter:" || exit 1
    # Strip pasted whitespace/newlines.
    RFB_API_DB_PASSWORD="${RFB_API_DB_PASSWORD//[$'\r\n']/}"
    RFB_API_DB_PASSWORD="${RFB_API_DB_PASSWORD#"${RFB_API_DB_PASSWORD%%[![:space:]]*}"}"
    RFB_API_DB_PASSWORD="${RFB_API_DB_PASSWORD%"${RFB_API_DB_PASSWORD##*[![:space:]]}"}"
    if [[ -z "$RFB_API_DB_PASSWORD" || "$RFB_API_DB_PASSWORD" == "[YOUR-PASSWORD]" || "$RFB_API_DB_PASSWORD" == postgres*://* ]]; then
      warn "That doesn't look like a password (empty, the [YOUR-PASSWORD] placeholder, or a full URL). Paste only the password."
      continue
    fi
    ok "Received ${#RFB_API_DB_PASSWORD} characters"
    if command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1; then
      say "Testing the login against Supabase via Docker (the first run downloads the postgres image)..."
      if PGPASSWORD="$RFB_API_DB_PASSWORD" docker run --rm -e PGPASSWORD postgres:17 \
          psql "host=${SUPABASE_POOLER_HOST} port=6543 dbname=postgres user=rfb_api.${SUPABASE_PROJECT_REF} sslmode=require" \
          -tAc 'select current_user' 2>/dev/null | grep -qx rfb_api; then
        ok "Login as rfb_api works with that password"
        break
      fi
      warn "Supabase rejected that password (or couldn't be reached). It may also still be propagating after 'alter role'."
      confirm "Paste it again?" || exit 1
    else
      note "Docker isn't running, so the login can't be tested here."
      break
    fi
  done
  # Quote the password so ; = " ' in it can't break the connection string.
  PW_QUOTED="\"${RFB_API_DB_PASSWORD//\"/\"\"}\""
  CONN="Host=${SUPABASE_POOLER_HOST};Port=6543;Database=postgres;Username=rfb_api.${SUPABASE_PROJECT_REF};Password=${PW_QUOTED};SSL Mode=Require;Max Auto Prepare=0;No Reset On Close=true;Multiplexing=false;Maximum Pool Size=5"
  if ! gcloud secrets describe "$SECRET_NAME" --project "$GCP_PROJECT_ID" >/dev/null 2>&1; then
    run_now gcloud secrets create "$SECRET_NAME" --replication-policy=automatic --project "$GCP_PROJECT_ID"
  fi
  if printf '%s' "$CONN" | gcloud secrets versions add "$SECRET_NAME" --data-file=- --project "$GCP_PROJECT_ID" >/dev/null; then
    ok "Added a new version of $SECRET_NAME"
  else
    warn "adding the secret version failed"
    SKIPPED+=("gcloud secrets versions add $SECRET_NAME --data-file=-")
  fi
  unset RFB_API_DB_PASSWORD PW_QUOTED CONN
  sleep 2
fi

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "First deploy and Cloud Run check"
SERVICE_URL=$(service_field status.url)
# A service can exist with only failed revisions (e.g. the startup probe never passed); that still needs a deploy.
if [[ -z "$SERVICE_URL" || -z "$(service_field status.latestReadyRevisionName)" ]]; then
  SERVICE_URL=""
  # The trigger builds master, so the build config and Dockerfile must be merged there first.
  MISSING_ON_MASTER=()
  for f in api/cloudbuild.yaml api/Dockerfile; do
    gh api "repos/${REPO_SLUG}/contents/${f}?ref=master" >/dev/null 2>&1 || MISSING_ON_MASTER+=("$f")
  done
  if (( ${#MISSING_ON_MASTER[@]} )); then
    warn "master doesn't have ${MISSING_ON_MASTER[*]} yet, so the trigger has nothing to build."
    say "Those files arrive with the open PR that adds the API (spec #533 / PR #572)."
    say "Setup so far (stages 1-7) is complete and saved. Once that PR is merged to master, either"
    say "wait for the trigger to build it automatically, or re-run this wizard to continue from here."
    exit 0
  fi
  say "Cloud Run service '$SERVICE' doesn't exist yet. Running the trigger on master:"
  run_cmd gcloud builds triggers run "$TRIGGER" --region "$REGION" --project "$GCP_PROJECT_ID" --branch=master
  open_url "https://console.cloud.google.com/cloud-build/builds;region=${REGION}?project=${GCP_PROJECT_ID}"
  step "Watch the build. Expected: schema step, build, push (SHA-tagged image), deploy."
  note "If the deploy step fails, it retries with backoff for ~10 min while it waits for the schema gate."
  note "The newest migration must be in hosted supabase_migrations.schema_migrations (dup 0153 is #571)."
  pause "Build finished (green)? Press Enter."
  SERVICE_URL=$(service_field status.url)
  [[ -n "$SERVICE_URL" ]] || { warn "Service still not found. Check the build log, then re-run; I'll resume here."; exit 1; }
fi
IMAGE=$(service_field 'spec.template.spec.containers[0].image')
IMAGE_TAG="${IMAGE##*:}"
write_env SERVICE_URL "$SERVICE_URL"
write_env IMAGE_TAG "${IMAGE_TAG:-unknown}"
ok "Service URL: $SERVICE_URL"
ok "Image tag deployed: ${IMAGE_TAG:-unknown}"

MIN=$(service_field 'spec.template.metadata.annotations."autoscaling.knative.dev/minScale"')
MAX=$(service_field 'spec.template.metadata.annotations."autoscaling.knative.dev/maxScale"')
PROBE=$(service_field 'spec.template.spec.containers[0].startupProbe.httpGet.path')
[[ "${MIN:-0}" == "0" ]] && ok "min instances 0" || warn "min instances is $MIN (want 0)"
[[ "$MAX" == "2" ]] && ok "max instances 2" || warn "max instances is '$MAX' (want 2)"
[[ "$PROBE" == "/health/ready" ]] && ok "startup probe /health/ready" || warn "startup probe is '$PROBE' (want /health/ready)"
gcloud run services describe "$SERVICE" --region "$REGION" --project "$GCP_PROJECT_ID" --format=json 2>/dev/null \
  | grep -q "POSTGRES_CONNECTION_STRING" && ok "secret mapped to POSTGRES_CONNECTION_STRING" || warn "secret mapping not found"
CODE=$(curl -s -o /dev/null -w '%{http_code}' "${SERVICE_URL}/health" || true)
if [[ "$CODE" == "200" ]]; then ok "GET /health → 200 (public invoke works)"
else
  warn "GET /health → ${CODE:-no response}. If it's 403, an org policy blocked --allow-unauthenticated:"
  note "grant allUsers roles/run.invoker on the service, or adjust."
fi
pause "Press Enter to continue."

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "GitHub: branch protection and Actions secrets"
if ! command -v gh >/dev/null 2>&1 || ! gh auth status >/dev/null 2>&1; then
  warn "gh isn't installed or logged in (winget install GitHub.cli; gh auth login)."
  SKIPPED+=("Branch protection on master requiring ci-ok; confirm Actions has no secrets")
else
  PROTECTED=$(gh api "repos/${REPO_SLUG}/branches/master/protection" --jq '.required_status_checks.contexts[]?' 2>/dev/null || true)
  if grep -qx "ci-ok" <<<"$PROTECTED"; then
    ok "master already requires the 'ci-ok' check"
  else
    say "master doesn't require 'ci-ok' yet. That check name only exists once ci.yml has run on a PR."
    if confirm "Has ci.yml run on a PR (so ci-ok exists)?"; then
      PROTECTION_FILE=$(mktemp)
      printf '%s\n' '{"required_status_checks":{"strict":false,"contexts":["ci-ok"]},"enforce_admins":false,"required_pull_request_reviews":null,"restrictions":null}' > "$PROTECTION_FILE"
      run_cmd gh api -X PUT "repos/${REPO_SLUG}/branches/master/protection" --input "$PROTECTION_FILE"
      rm -f "$PROTECTION_FILE"
    else
      SKIPPED+=("Branch protection on master requiring ci-ok (after ci.yml has run on a PR)")
    fi
  fi
  REPO_SECRETS=$(gh secret list -R "$REPO_SLUG" 2>/dev/null | awk '{print $1}' || true)
  if [[ -z "$REPO_SECRETS" ]]; then
    ok "No repository Actions secrets"
  else
    warn "Repository secrets exist (the checklist wants none): $(tr '\n' ' ' <<<"$REPO_SECRETS")"
  fi
  step "Environment secrets can't be listed here. Check: github.com/${REPO_SLUG}/settings/environments"
  open_url "https://github.com/${REPO_SLUG}/settings/environments"
  pause "Environments have no secrets? Press Enter."
fi

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Cold start measurement and #534 summary"
SAVED_COLD=$(_existing COLD_START_TIMES || true)
MEASURE=yes
if [[ -n "$SAVED_COLD" ]]; then
  ok "Already measured: $SAVED_COLD"
  confirm "Measure again?" || MEASURE=no
fi
if [[ "$MEASURE" == "yes" ]]; then
  say "Five cold requests, each after ${COLD_GAP:-16} idle minutes. Do not add keep-warm."
  say "This takes about 80 minutes. You can leave it running; press Enter during a countdown to skip it."
  COLD_TIMES=()
  for i in 1 2 3 4 5; do
    countdown $(( ${COLD_GAP:-16} * 60 )) "Run $i/5, waiting for the service to scale to zero"
    t=$(curl -s -o /dev/null -w '%{time_total}' "${SERVICE_URL}/health" || echo "failed")
    printf '  cold #%s: %ss\n' "$i" "$t"
    COLD_TIMES+=("$t")
  done
  WARM=$(curl -s -o /dev/null -w '%{time_total}' "${SERVICE_URL}/health" || echo "failed")
  printf '  warm: %ss\n' "$WARM"
  write_env COLD_START_TIMES "${COLD_TIMES[*]} (warm ${WARM})"
  SAVED_COLD="${COLD_TIMES[*]} (warm ${WARM})"
fi

say ""
say "Paste this on issue #534:"
printf '    Service URL:      %s\n' "$SERVICE_URL"
printf '    Image deployed:   %s\n' "${IMAGE_TAG:-unknown}"
printf '    Cold starts (s):  %s\n' "$SAVED_COLD"
say "Also attach: confirmation of the GBP 1 budget alerts, and that ci-ok is required on master."
pause "Posted to #534? Press Enter."

finish
